# Generated by Django 3.2.11 on 2022-02-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220202_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-finished']},
        ),
    ]
